config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='users/index.html'), name='home'),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

urlpatterns = [

]

users/urls.py
from django.urls import path
from .views import signup, log_in, log_out

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]

myapp/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


# Create your models here.
class Comment(models.Model):
    author = models.CharField(max_length=50)
    content = models.TextField()

    # the required fields to enable a generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__(self):
        return self.author


class Post(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    body = models.TextField()
    comments = GenericRelation(Comment)

    def __str__(self):
        return self.title


class Profile(models.Model):
    about = models.TextField()
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    comments = GenericRelation(Comment)

    def __str__(self):
        return f'profile of {self.user.username}'

users/models.py
import os

from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import CustomUserManager

# from io import BytesIO
# from django.core.files import File
# from PIL import Image, ImageDraw, ImageFont


# Create your models here.

class CustomUser(AbstractUser):
    email = models.EmailField('email adress', unique=True)
    image = models.ImageField('user_photo', blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager

    # def save(self, *args, **kwargs):
    #     try:
    #         if len(self.image) > 0:
    #             img = Image.new('RGB', (400, 400), color=(73, 109, 137))
    #             d = ImageDraw.Draw(img)
    #             fnt = ImageFont.truetype("Pillow/Tests/fonts/FreeMono.ttf", size=150)
    #             d.text((80, 120), 'H W', fill=(255, 255, 255), font=fnt)
    #             fname = f"{self.username}" + ".png"
    #             buffer = BytesIO()
    #             img.save(buffer, 'PNG')
    #             self.image.save(fname, File(buffer), save=False)
    #             img.close()
    #     except:
    #         pass

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'image')


class LogInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

myapp/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse

from .forms import SignUpForm, LogInForm


# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def log_in(request):
    error = False
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = LogInForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('home')
            else:
                error = True
    else:
        form = LogInForm()
    return render(request, 'users/login.html', {'form': form, 'errors': error})

def log_out(request):
    logout(request)
    return redirect(reverse('users:login'))

users/templates/users/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'users/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'users/css/style_register.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
</head>
<body>
{% block nav %}

{% endblock %}
{% block content %}

{% endblock %}

</body>
</html>

users/templates/users/index.html
{% extends 'users/base.html' %}

{% block nav %}
    <div class="navbar">
        <a class="active" href="{% url 'home' %}"><i class="fa fa-fw fa-home"></i> Home</a>
        <a href="#"><i class="fa fa-fw fa-search"></i> Search</a>
        <a href="#"><i class="fa fa-fw fa-envelope"></i> Contact</a>
        {% if user.is_authenticated %}
            <a href="#"><i class="fa fa-fw fa-user"></i> Log out</a>
        {% else %}
            {{ user.username }}
            <a href="{% url 'users:login' %}"><i class="fa fa-fw fa-sign-in"></i> Login</a>
            <a href="{% url 'users:signup' %}"><i class="fa fa-fw fa-sign-out"></i> Sign up</a>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% load add_attr %}

{#{% block content %}#}
{#    {% if errors %}#}
{#        <p>parol yoki email xato</p>#}
{#    {% endif %}#}
{##}
{#    <form action="" method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        {{ form.errors }}#}
{#        <input type="submit" value="submit">#}
{#    </form>#}
{##}
{##}
{#{% endblock %}#}
{% block nav %}
{% include 'users/index.html' %}
{% endblock %}

{% block content %}
    {#    {{ 'salom'|add_attr:'birnimalarni yuborish kerak edi lekin men  nima yozishni bilmadim bu shunchaki test' }}#}
    {% if errors %}
        <p>parol yoki email xato</p>
    {% endif %}
{#    {{ form.email|add_placeholder:'font_form' }}#}
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static 'users/images/signin-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'users:signup' %}" class="signup-image-link">Create an account</a>
                </div>

                <div class="signin-form">
                    <h2 class="form-title">Sign up</h2>
                    <form method="POST" class="register-form" id="login-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            {{ form.email }}
                            {#                        <input type="text" name="your_name" id="your_name" placeholder="Your email"/>#}
                        </div>
                        <div class="form-group">
                            <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term"/>
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember
                                me</label>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/signup.html
{% extends 'users/base.html' %}
{% load add_attr %}
{% load static %}

{% block nav %}
    {% include 'users/index.html' %}
{% endblock %}
{% block content %}
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>
                    <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">

                            <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            {{ form.username|add_classes:form.username.label }}
                        </div>
                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            {{ form.email|add_classes:form.email.label }}
                        </div>

                        <div class="form-group">
                            <label class="file">
                                <input type="file" id="file" aria-label="File browser example">
                                <span class="file-custom"></span>
                            </label>
                            <label for="pass"><i class="zmdi zmdi-image"></i></label>
                            {{ form.image|add_classes:form.email.label }}
                        </div>
                        <div class="form-group">
                            <label for="re_pass"><i class="zmdi zmdi-lock"></i></label>
                            {{ form.password1|add_classes:form.password1.label }}
                        </div>
                        <div class="form-group">
                            <label for="re_pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            {{ form.password2|add_classes:form.password2.label }}
                        </div>

                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term"/>
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all
                                statements in <a href="#" class="term-service">Terms of service</a></label>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                        </div>
                    </form>
                </div>
                {{ form.errors }}
                <div class="signup-image">
                    <figure><img src="{% static 'users/images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'users:login' %}" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}